{% set name = "supafunc" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a5b33c8baecb6b5297d25da29a2503e2ec67ee6986f3d44c137e651b8a59a17d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
    - setuptools
  run:
    - python >={{ python_min }}
    - httpx >=0.26.0,<0.28
    - strenum >=0.4.15,<0.5

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - supafunc

about:
  home: https://github.com/supabase-community/functions-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python Library for Supabase Functions
  description: |
    Python Library for Supabase Functions

extra:
  recipe-maintainers:
    - timkpaine
    - J0
    - anand2312
