{% set name = "supafunc" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 64cdf331f5a3f2afc7c181697d4723efc084620ea66611f3211dd5ecbef595c1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
    - setuptools
  run:
    - python >={{ python_min }}
    - httpx >=0.26.0,<0.28

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - supafunc

about:
  home: https://github.com/supabase-community/functions-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python Library for Supabase Functions
  description: |
    Python Library for Supabase Functions

extra:
  recipe-maintainers:
    - timkpaine
    - J0
    - anand2312
