{% set name = "supafunc" %}
{% set version = "0.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a6466d78bdcaa58b7f0303793643103baae8106a87acd5d01e196179a9d0d024

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python >=3.8
    - pip
    - poetry
  run:
    - python >=3.8
    - httpx >=0.24.0,<0.26

test:
  requires:
    - pip
  imports:
    - supafunc

about:
  home: https://github.com/supabase-community/functions-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python Library for Supabase Functions
  description: |
    Python Library for Supabase Functions

extra:
  recipe-maintainers:
    - timkpaine
    - J0
    - anand2312
