{% set name = "supafunc" %}
{% set version = "0.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 68824a9a7bcccf5ab1e038cda632ba47cba27f2a7dc606014206b56f5a071de2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
    - setuptools
  run:
    - python >={{ python_min }}
    - httpx >=0.26.0,<0.28
    - strenum >=0.4.15,<0.5

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - supafunc

about:
  home: https://github.com/supabase-community/functions-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python Library for Supabase Functions
  description: |
    Python Library for Supabase Functions

extra:
  recipe-maintainers:
    - timkpaine
    - J0
    - anand2312
